version: '3.2'

services:
  todo-frontend:
    container_name: "${PROJECT_NAME}_frontend_${ENV}"
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c 'python manage.py collectstatic --noinput
      && gunicorn todo.wsgi:application --workers 4 --bind 0.0.0.0:$WEB_PORT --reload
      '
    volumes:
      - "./:/code"
    ports:
      - $WEB_PORT:8000

  nginx:
    container_name: "${PROJECT_NAME}_frontend_nginx_${ENV}"
    image: nginx:latest
    volumes:
      - "./:/code/"
      - "./nginx/nginx-$ENV.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - $NGINX_PORT:80
      - 443:443
    depends_on:
      - todo-frontend
    restart: always
    links:
      - todo-frontend:todo-frontend
